spring.application.name=movie-info-service
server.port=8082

api.key=b0af84324ea41ca39f4311c9156e94e3

# MongoDB Connection Settings
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=movie_db

# Optional: To see the queries in the logs (useful for debugging your cache logic)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG